[package]
name = "cmwemu"
version = "0.25.2"
edition = "2024"
authors = ["sha0coder"]
license = "Apache-2.0"
rust-version = "1.88"
description = "C ABI bindings for libmwemu (x86/x64/arm64 emulator)."
repository = "https://github.com/mwemuorg/cmwemu"

[lib]
name = "cmwemu"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
libmwemu = { path = "../libmwemu", version = "0.25.4" }

[build-dependencies]
cbindgen = "0.29"
